# Generated by Django 4.1.13 on 2024-03-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginout0', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userr',
        ),
    ]
