# Generated by Django 4.1.13 on 2024-03-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginout0', '0002_rename_user_userr'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=100)),
                ('no_of_seats', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('pictures', models.ImageField(upload_to='car_pictures/')),
                ('standard_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Userr',
        ),
    ]
