# Generated by Django 4.1.13 on 2024-03-26 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginout0', '0005_customerbooked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerBooked',
        ),
    ]
