# Generated by Django 4.1.13 on 2024-03-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginout0', '0009_bookings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
